<?php


/**
 * Implementation of hook_node_info)().
 */
function cforge_events_node_info(){
  $types['event'] = array(
    'name' => 'Event',
    'module' => 'cforge_events',
    'base' => 'cforge_events',
    'description' => t('Content type with date field'),
    'has_title' => TRUE,
    'title_label' => t('Title'),
    'has_body' => TRUE,
  );
  return $types;
}


/**
 * Implementation of hook_form)().
 */
function cforge_events_form(&$node, $form_state){
  return node_content_form($node, $form_state);
}


function cforge_events_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'cforge_events'),
  );
}
