<?php

/*
 * implements hook_views_api
 * tells views where to look for its include files
 * in this case, in the same directory as this file
 */
function likeabee_marketplace_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'likeabee_marketplace'),
  );
}

function likeabee_marketplace_block_info_alter(&$blocks, $theme) {
  if ($theme != 'kaveret'; return;
  //just alter the blocks you care about
  $blocks[module_name][delta]['region'] = 'blah';
  $blocks[module_name][delta]['weight'] = 1;
  $blocks[module_name][delta]['visibility'] = BLOCK_VISIBILITY_LISTED or BLOCK_VISIBILITY_NOTLISTED;
  $blocks[module_name][delta]['pages'] = "<front>\nnode*";
}
