<?php

/*
 * implements hook_views_api
 * tells views where to look for its include files
 * in this case, in the same directory as this file
 */
function likeabee_marketplace_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'likeabee_marketplace'),
  );
}

/*
 * implements hook_block_info_alter
 * fixes the blocks, regardless of edits made by user 1
 */
function likeabee_marketplace_block_info_alter($blocks, $theme) {
  if ($theme != 'beezy') return;
  $blocks['uc_cart']['cart'] = array(
    'status' => '1',
    'weight' => '0',
    'region' => '-1',
    'custom' => '0',
    'visibility' => '0',
    'pages' => 'admin*',
    'title' => '',
    'cache' => '-1',
    'i18n_mode' => '0',
  ) + $blocks['uc_cart']['cart'];
  $blocks['uc_catalog']['catalog'] = array(
    'status' => '1',
    'weight' => '0',
    'region' => '-1',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '5',
    'i18n_mode' => '0',
) + $blocks['uc_catalog']['catalog'];
}
