<?php

/*
 * implements hook_install
 */
function likeabee_config_install() {
  likeabee_setup_filters();
}


function likeabee_setup_filters() {
  drupal_set_message("Setting up the filters and ckeditor - this has not been tested yet...");

  db_truncate('filter_format')->execute();
  db_query("INSERT INTO {filter_format} (`format`, `name`, `cache`, `status`, `weight`) VALUES
('filtered_html', 'Filtered HTML', 1, 1, 0),
('full_html', 'Full HTML', 1, 1, 1),
('php_code', 'PHP code', 0, 1, 11),
('plain_text', 'Plain text', 1, 1, 10);");

  db_truncate('filter')->execute();
  db_query("INSERT INTO {filter} VALUES
('filtered_html', 'filter', 'filter_autop', 2, 1, 0x613a303a7b7d),
('filtered_html', 'filter', 'filter_html', 1, 1, 0x613a333a7b733a31323a22616c6c6f7765645f68746d6c223b733a37343a223c613e203c656d3e203c7374726f6e673e203c636974653e203c626c6f636b71756f74653e203c636f64653e203c756c3e203c6f6c3e203c6c693e203c646c3e203c64743e203c64643e223b733a31363a2266696c7465725f68746d6c5f68656c70223b693a313b733a32303a2266696c7465725f68746d6c5f6e6f666f6c6c6f77223b693a303b7d),
('filtered_html', 'filter', 'filter_htmlcorrector', 10, 1, 0x613a303a7b7d),
('filtered_html', 'filter', 'filter_html_escape', -10, 0, 0x613a303a7b7d),
('filtered_html', 'filter', 'filter_url', 0, 1, 0x613a313a7b733a31373a2266696c7465725f75726c5f6c656e677468223b693a37323b7d),
('full_html', 'filter', 'filter_autop', 1, 1, 0x613a303a7b7d),
('full_html', 'filter', 'filter_html', -10, 0, 0x613a333a7b733a31323a22616c6c6f7765645f68746d6c223b733a37343a223c613e203c656d3e203c7374726f6e673e203c636974653e203c626c6f636b71756f74653e203c636f64653e203c756c3e203c6f6c3e203c6c693e203c646c3e203c64743e203c64643e223b733a31363a2266696c7465725f68746d6c5f68656c70223b693a313b733a32303a2266696c7465725f68746d6c5f6e6f666f6c6c6f77223b693a303b7d),
('full_html', 'filter', 'filter_htmlcorrector', 10, 1, 0x613a303a7b7d),
('full_html', 'filter', 'filter_html_escape', -10, 0, 0x613a303a7b7d),
('full_html', 'filter', 'filter_url', 0, 1, 0x613a313a7b733a31373a2266696c7465725f75726c5f6c656e677468223b693a37323b7d),
('php_code', 'filter', 'filter_autop', 0, 0, 0x613a303a7b7d),
('php_code', 'filter', 'filter_html', -10, 0, 0x613a333a7b733a31323a22616c6c6f7765645f68746d6c223b733a37343a223c613e203c656d3e203c7374726f6e673e203c636974653e203c626c6f636b71756f74653e203c636f64653e203c756c3e203c6f6c3e203c6c693e203c646c3e203c64743e203c64643e223b733a31363a2266696c7465725f68746d6c5f68656c70223b693a313b733a32303a2266696c7465725f68746d6c5f6e6f666f6c6c6f77223b693a303b7d),
('php_code', 'filter', 'filter_htmlcorrector', 10, 0, 0x613a303a7b7d),
('php_code', 'filter', 'filter_html_escape', -10, 0, 0x613a303a7b7d),
('php_code', 'filter', 'filter_url', 0, 0, 0x613a313a7b733a31373a2266696c7465725f75726c5f6c656e677468223b693a37323b7d),
('php_code', 'php', 'php_code', 0, 1, 0x613a303a7b7d),
('plain_text', 'filter', 'filter_autop', 2, 1, 0x613a303a7b7d),
('plain_text', 'filter', 'filter_html', -10, 0, 0x613a333a7b733a31323a22616c6c6f7765645f68746d6c223b733a37343a223c613e203c656d3e203c7374726f6e673e203c636974653e203c626c6f636b71756f74653e203c636f64653e203c756c3e203c6f6c3e203c6c693e203c646c3e203c64743e203c64643e223b733a31363a2266696c7465725f68746d6c5f68656c70223b693a313b733a32303a2266696c7465725f68746d6c5f6e6f666f6c6c6f77223b693a303b7d),
('plain_text', 'filter', 'filter_htmlcorrector', 10, 0, 0x613a303a7b7d),
('plain_text', 'filter', 'filter_html_escape', 0, 1, 0x613a303a7b7d),
('plain_text', 'filter', 'filter_url', 1, 1, 0x613a313a7b733a31373a2266696c7465725f75726c5f6c656e677468223b693a37323b7d);
");

  variable_set('filter_fallback_format', 'plain_text');

  //now CKeditor
  //rename the formats as installed by the ckeditor module
  db_query("TRUNCATE table {ckeditor_input_format}");
  db_query("INSERT INTO {ckeditor_input_format} (name, format) VALUES ('Advanced', 'filtered_html'), ('Full', 'full_html');");

  $settings = array (
    'Advanced' => array (
      'ss' => '2',
      'default' => 't',
      'show_toggle' => 't',
      'skin' => 'kama',
      'uicolor' => 'default',
      'uicolor_textarea' => '<p>
  Click the <strong>UI Color Picker</strong> button to set your color preferences.</p>
',
      'uicolor_user' => 'default',
      'toolbar' => '[
      [\'Bold\',\'Italic\',\'Underline\',\'-\',\'BulletedList\',\'-\'],
      [\'JustifyLeft\',\'JustifyCenter\',\'JustifyRight\',\'-\',\'BidiLtr\',\'BidiRtl\'],
      [\'Link\',\'Unlink\']
  ]',
      'expand' => 't',
      'width' => '100%',
      'lang' => 'en',
      'auto_lang' => 't',
      'language_direction' => 'ltr',
      'enter_mode' => 'p',
      'shift_enter_mode' => 'br',
      'font_format' => 'p;div;pre;address;h1;h2;h3;h4;h5;h6',
      'custom_formatting' => 'f',
      'formatting' => array (
        'custom_formatting_options' => array (
          'indent' => 'indent',
          'breakBeforeOpen' => 'breakBeforeOpen',
          'breakAfterOpen' => 'breakAfterOpen',
          'breakAfterClose' => 'breakAfterClose',
          'breakBeforeClose' => 0,
          'pre_indent' => 0,
        ),
      ),
      'css_mode' => 'none',
      'css_path' => '',
      'css_style' => 'theme',
      'styles_path' => '',
      'filebrowser' => 'none',
      'filebrowser_image' => '',
      'filebrowser_flash' => '',
      'UserFilesPath' => '%b%f/',
      'UserFilesAbsolutePath' => '%d%b%f/',
      'ckeditor_load_method' => 'ckeditor.js',
      'ckeditor_load_time_out' => '0',
      'forcePasteAsPlainText' => 'f',
      'html_entities' => 't',
      'scayt_autoStartup' => 'f',
      'theme_config_js' => 'f',
      'js_conf' => '',
      'loadPlugins' => array (
        'ckeditor_link' => array (
          'name' => 'drupal_path',
          'desc' => 'CKEditor Link - A plugin to easily create links to Drupal internal paths',
          'path' => '%base_path%sites/all/modules/ckeditor_link/plugins/link/',
          'buttons' => false,
        ),
        'drupalbreaks' => array (
          'name' => 'drupalbreaks',
          'desc' => 'Plugin for inserting Drupal teaser and page breaks.',
          'path' => '%base_path%%plugin_dir%drupalbreaks/',
          'buttons' => array (
            'DrupalBreak' => array (
              'label' => 'DrupalBreak',
              'icon' => 'images/drupalbreak.png',
            ),
          ),
          'default' => 't',
        ),
        'tableresize' => array (
          'name' => 'tableresize',
          'desc' => 'Table Resize plugin',
          'path' => '%base_path%%editor_path%plugins/tableresize/',
          'buttons' => false,
          'default' => 't',
        ),
      ),
    ),
    'CKEditor Global Profile' => array (
      'ckeditor_path' => '%m/ckeditor',
    ),
    'Full' => array (
      'ss' => '2',
      'default' => 't',
      'show_toggle' => 't',
      'skin' => 'kama',
      'uicolor' => 'default',
      'uicolor_textarea' => '<p>
    Click the <strong>UI Color Picker</strong> button to set your color preferences.</p>
  ',
      'uicolor_user' => 'default',
      'toolbar' => '[
      [\'Bold\',\'Italic\',\'Underline\',\'-\',\'BulletedList\',\'-\',\'JustifyLeft\',\'JustifyCenter\',\'JustifyRight\',\'-\',\'BidiLtr\',\'BidiRtl\'],
      [\'Link\',\'Unlink\'],
      [\'TextColor\',\'BGColor\',\'-\',\'PasteFromWord\',\'Image\',\'Table\']
  ]',
      'expand' => 't',
      'width' => '100%',
      'lang' => 'en',
      'auto_lang' => 't',
      'language_direction' => 'ltr',
      'enter_mode' => 'p',
      'shift_enter_mode' => 'br',
      'font_format' => 'p;div;pre;address;h1;h2;h3;h4;h5;h6',
      'custom_formatting' => 'f',
      'formatting' => array (
        'custom_formatting_options' => array (
          'indent' => 'indent',
          'breakBeforeOpen' => 'breakBeforeOpen',
          'breakAfterOpen' => 'breakAfterOpen',
          'breakAfterClose' => 'breakAfterClose',
          'breakBeforeClose' => 0,
          'pre_indent' => 0,
        ),
      ),
      'css_mode' => 'none',
      'css_path' => '',
      'css_style' => 'theme',
      'styles_path' => '',
      'filebrowser' => 'none',
      'filebrowser_image' => '',
      'filebrowser_flash' => '',
      'UserFilesPath' => '%b%f/',
      'UserFilesAbsolutePath' => '%d%b%f/',
      'ckeditor_load_method' => 'ckeditor.js',
      'ckeditor_load_time_out' => '0',
      'forcePasteAsPlainText' => 'f',
      'html_entities' => 't',
      'scayt_autoStartup' => 'f',
      'theme_config_js' => 'f',
      'js_conf' => '',
      'loadPlugins' => array (
        'ckeditor_link' => array (
          'name' => 'drupal_path',
          'desc' => 'CKEditor Link - A plugin to easily create links to Drupal internal paths',
          'path' => '%base_path%sites/all/modules/ckeditor_link/plugins/link/',
          'buttons' => false,
        ),
        'drupalbreaks' => array (
          'name' => 'drupalbreaks',
          'desc' => 'Plugin for inserting Drupal teaser and page breaks.',
          'path' => '%base_path%%plugin_dir%drupalbreaks/',
          'buttons' => array (
            'DrupalBreak' => array (
              'label' => 'DrupalBreak',
              'icon' => 'images/drupalbreak.png',
            ),
          ),
          'default' => 't',
        ),
        'tableresize' => array (
          'name' => 'tableresize',
          'desc' => 'Table Resize plugin',
          'path' => '%base_path%%editor_path%plugins/tableresize/',
          'buttons' => false,
          'default' => 't',
        ),
      ),
    ),
  );
  foreach ($settings as $name => $setting) {
    db_query("REPLACE INTO {ckeditor_settings} (name, settings) VALUES ('$name', :settings)",
      array(':settings' => serialize($setting))
    );
  }

  drupal_set_message('Some test permissions have been set, but permissions nor roles were determined at the time of writing');

  $all_permissions = array(
    DRUPAL_ANONYMOUS_RID => array(
      'use text format filtered_html'
    ),
    DRUPAL_AUTHENTICATED_RID => array(
      'use text format filtered_html',
      'use text format full_html',
    ),
  );

  filter_formats_reset();
  foreach ($all_permissions as $rid => $permissions) {
    user_role_grant_permissions($rid, $permissions);
  }



}