<?php

/*
 * I hope that this module will one day conform to a Plugin API for each likeabee section
 */

function likeabee_resources_menu() {
  $items['resources'] = array(
    'title' => 'Resources exchange',
    'description' => 'Buy, sell, pay, swop or gift!',
    'page callback' => 'likeabee_resources_default_page',
    'access callback' => 'user_access',
    'access arguments' => array('transact'),
    'menu_name' => 'main-menu',
    'weight' => 1
  );
  /*
  $items['resources/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'Buy, sell, pay, swop or gift!',
    'page callback' => 'likeabee_resources_default_page',
    'access callback' => 'user_access',
    'access arguments' => array('transact'),
    'menu_name' => 'main-menu',
    'weight' => 1
  );*/
  $items['resources/marketplace'] = array(
    'title' => 'Marketplace',
    'description' => 'Buy, sell, pay, swop or gift!',
    'page callback' => 'likeabee_resources_marketplace',
    'page callback' => 'likeabee_resources_default_page',
    'access callback' => 'user_access',
    'access arguments' => array('transact'),
    'menu_name' => 'main-menu',
    'weight' => 2
  );
/*  this is a view
  $items['resources/statement'] = array(
    'title' => 'Statement',
    'description' => 'Buy, sell, pay, swop or gift!',
    'page callback' => 'likeabee_resources_statement',
    'page callback' => 'likeabee_resources_default_page',
    'access callback' => 'user_access',
    'access arguments' => array('transact'),
    'menu_name' => 'main-menu',
    'weight' => 3
  );
*/
  $items['resources/another'] = array(
    'title' => 'Another page',
    'description' => 'Buy, sell, pay, swop or gift!',
    'page callback' => 'likeabee_resources_other',
    'page callback' => 'likeabee_resources_default_page',
    'access callback' => 'user_access',
    'access arguments' => array('transact'),
    'menu_name' => 'main-menu',
    'weight' => 4
  );
  return $items;
}


function likeabee_resources_help($path, $args) {

  if ($args[0] == 'resources') {
    //unhide the menu tabs!!!
    drupal_add_css('#page #main-menu{display:block;}', array('type' => 'inline'));
  }
  if ($path == 'resources') {
    $help[] = t('This is the local economy section. Here you can find what you need pay in Beez or in Shekels, or advertise yourself or your needs.');
    $help[] = t('Find out more about our currency, !beez', array('!beez' => l('Beez', 'help/beez')));
    return implode(' ', $help);
  }
}

function likeabee_resources_default_page() {
  return 'This front page might be populated only by blocks. If we make an internal API, it would help with this.
    Currently a ccss hack is being used to reveal the main-menu, which is concealed in the theme.
    The menu_block module is here showing level 2 of the main-menu. I suggeest this approach over quicktabs.';
}

function likeabee_resources_marketplace() {
  return 'This page will be a faceted search view of products. We could use the offers/wants module for now, but I think we should get on with installing commerce.';

}

function likeabee_resources_other() {
  return "This page is filling up space. could be used to show other people's transaction, system stats, special offers, or perhaps to talk about how many beez have been issued and redeemed.";
}