<?php

/*
 * This module is discontinued and the whole approach of defining sections with a hook
 * because the theme is all intertwined with the menu system already
 * and I'm not here to re-engineer the whole site.
 */

/*
 * implements hook_menu
 */
function likeabee_menu() {
  $items['content/groups'] = array(
    'title' => "Groups",
    'page callback' => 'views_embed_view',
    'page arguments' => array('list_of_groups', 'block'),
    'access callback' => TRUE,
    'access arguments' => array('access content'),
    'weight' => 1
  );
  //this allows us to used views in code without modifications, but which explose blocks rather than pages
  $items['content/groups/editors_choice'] = array(
    'title' => "Editor's choice",
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1
  );
  $items['content/groups/popular'] = array(
    'title' => "Popular",
    'page callback' => 'views_embed_view',
    'page arguments' => array('list_of_groups', 'block_1'),
    'access callback' => TRUE,
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2
  );
  $items['content/groups/all'] = array(
    'title' => "All",
    'page callback' => 'views_embed_view',
    'page arguments' => array('list_of_groups', 'block_2'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3
  );
  return $items;
}


function likeabee_hook_info() {
  return array(
    'likeabee_section' => array()
  );
}

/*
 * implements hook_likeabee_section
 */
function likeabee_likeabee_section() {
  return array(
    'resources' => array(//this is the path to the section
      'title' => 'Resources',//this will be translated later
      'icon' => ''
    )
  );
}

function likeabee_node_view_alter(&$build, $node) {
  $build['section_chooser'] = module_invoke('menu_block', 'block_view', 'menu_block_3');
  $build['events'] = group_summary(t("Group's events"), 'event');
  $build['poll'] = group_summary(t("Group's polls"), 'poll');
  $build['video'] = group_summary(t("Group's videos"), 'video');
  $build['discussion'] = group_summary(t("Group's discussions"), 'discussion');
  $build['documents'] = group_summary(t("Group's documents"), 'document');
  //debug($node, 0, 1);
}

function group_summary($title, $type) {
  static $w = 1;
  return array(
    '#theme' => 'likeabee_groups_summary',
    '#weight' => $w++,
    '#title' => $title,
    '#type' => $type,
    '#view' => array('groups_content_preview', 'groups_choice'),
    '#gid' => 161
  );
}

function likeabee_theme() {
  $items['likeabee_groups_summary'] = array(
    'variables' => array(
      'title' => '',
      'type' => '',
      'view' => '',
      'gid' => 0
    )
  );
  return $items;
}
function theme_likeabee_groups_summary($variables) {
  static $flip = 'even';
  $flip = $flip == 'even' ? 'odd' : 'even';
  $output[] = "<div class = \"group-summary-$type $flip\" ><h2>".$variables['title'].'</h2>';
  $view = $variables['view'][0];
  $display = $variables['view'][1];
  $output[] = '<div class = "link-all">'. l('See All', "content/group/".$variables['type'].'/'. $variables['gid']) . '</div>';//we need a consistent name for the 'all display'
  $output[] = views_embed_view($view, $display, $variables['type']);
  return implode("\n", $output) .'<div><!--End group summary-->';
}

function likeabee_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'likeabee'),
  );
}