<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once 'kaveret_general.features.inc';
/**
 * Build page breadcrumbs.
 *
 * @TODO: Currently only supports homepage, offers page and My-Wallet.
 */
function kaveret_general_get_breadcrumbs() {
  global $language;

  $dir = $language->direction == LANGUAGE_RTL ? 'rtl' : 'ltr';

  $items = array(l(t('Main Page'), ''));

  $item = menu_get_item();
  switch ($item['path']) {
    case 'front':
      $items[] = "<span dir=\"$dir\">" . t('Marketplace') . '</span>';
      break;

    case 'offers':
      $items[] = "<span dir=\"$dir\">" . t('Marketplace') . '</span>';
      break;

    case 'my-wallet':
      $items[] = "<span dir=\"$dir\">" . l(t('Resource Exchange'), '') . '</span>';
      $items[] = "<span dir=\"$dir\">" . t('My Wallet') . '</span>';
      break;

    case 'directory':
      $items[] = "<span dir=\"$dir\">" . l(t('Resource Exchange'), '') . '</span>';
      $items[] = "<span dir=\"$dir\">" . l(t('Marketplace'), '') . '</span>';
      $items[] = "<span dir=\"$dir\">" . t('Full Directory List') . '</span>';
      break;
  }

  return implode(' <span class="arrow"></span> ', $items);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function kaveret_general_form_user_login_block_alter(&$form, &$form_state){
  $items = array();
  if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
    $items[] = l(t('Sign Up'), 'user/register', array('attributes' => array('title' => t('Create a new user account.'))));
  }
  $items[] = l(t('Forgot your password?'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
  $form['links'] = array('#markup' => theme('item_list', array('items' => $items)));
}
