<?php
/**
 * @file
 * Drupal needs this blank file.
 */


/**
 * Build page breadcrumbs.
 *
 * @TODO: Currently only supports homepage and offers page.
 */
function kaveret_general_get_breadcrumbs() {
  $items = array(l(t('Home'), ''));

  $item = menu_get_item();
  switch ($item['path']) {
    case 'front':
    case 'offers':
      $items[] = t('Offers/ Requests');
      break;
  }

  return implode(' <span class="arrow">&gt;</span> ', $items);
}
