<?php

/*
 * implements hook_menu_alter
 */
function cforge_yell_menu_alter(&$items) {
//  $items['admin/config/ow']['menu_name'] = 'setup';
//  $items['admin/config/ow']['title'] = t('offers & wants');

  $items['node/add/proposition']['menu_name'] = 'user-menu';
  unset($items['node/add/proposition']['title callback']);

  $vocab = taxonomy_vocabulary_machine_name_load('offers_wants_categories');
  $tree = taxonomy_get_tree($vocab->vid);
  if (empty($tree)) {
    module_load_install('cforge_yell');
    $vocabs = array_keys(yell_vocabs());
    foreach ($vocabs as $vocabname) {
      $links[] = l($vocabname, 'cforge_yell_import/'.$vocabname);
    }
    drupal_set_message(t('Choose default categories for the offers/wants directory: !link', array('!link' => implode(', ', $links))));
    $items['cforge_yell_import'] = array(
      'page callback' => 'yell_vocabs_import',
      'page arguments' => array("$vocab->vid", 1),
      'access arguments' => array('local admin'),
      'include file' => drupal_get_path('module', 'cforge_yell').'/cforge_yell.install'
    );
  }
}
function cforge_yell_menu_link_alter(&$link) {
  if ($link['link_path'] == 'node/add/proposition') {
    $link['plid'] = 0;
    $link['weight'] = -1;
  }
}

function cforge_yell_views_default_views_alter(&$views) {
//  $views['ow_offers']->display['all']->handler->options['menu']['weight'] = 1;
//  $views['ow_wants']->display['all']->handler->options['menu']['weight'] = 2;
}