<?php

/**
 * @file
 * Code for the Kaveret OG feature.
 */

include_once 'kaveret_og.features.inc';

/**
 * Implements hook_user_insert().
 *
 * Attach new users to the default community.
 */
function kaveret_og_user_insert($edit, $account) {
  // Do nothing in case there's no default community.
  if (!variable_get('kaveret_og_single_community')) {
    return;
  }

  $nid = variable_get('kaveret_og_default_community');
  og_group('node', $nid, array('entity_type' => 'user', 'entity' => $account));
}

/**
 * Implements hook_og_context_negotiation_info().
 */
function kaveret_og_og_context_negotiation_info() {
  $providers = array();

  $providers['kaveret_og'] = array(
    'name' => t('Single community'),
    'description' => t('Provides default context for a single-community installation.'),
    'callback' => 'kaveret_og_og_context_handler',
  );

  return $providers;
}

/**
 * OG-context handler.
 *
 * Retreive the default community group ID.
 */
function kaveret_og_og_context_handler() {
  return array(
    'node' => array(variable_get('kaveret_og_default_community')),
  );
}
