<?php

 ini_set('display_errors', '1');

/*
 * I hope that this module will one day conform to a Plugin API for each likeabee section
 */

function likeabee_resources_menu() {

  $items['resources'] = array(
    'title' => 'Resources exchange',
    'description' => 'Buy, sell, pay, swop or gift!',
    'page callback' => 'resources_beeziest',
    'access arguments' => array('transact'),
    'menu_name' => 'menu-main-icons',
    'weight' => 0
  );

  $items['resources/dashboard'] = array(
    'title' => 'Beeziest members',
    'description' => 'Buy, sell, pay, swop or gift!',
    'page callback' => 'resources_beeziest',
    'access arguments' => array('transact'),
    'menu_name' => 'main-menu',
    'weight' => 1
  );

  $items['resources/my_beez'] = array(
    'title' => 'My Beez',
    'description' => 'Buy, sell, pay, swop or gift!',
    'page callback' => 'resources_my_beez',
    'access arguments' => array('transact'),
    'menu_name' => 'main-menu',
    'weight' => 1
  );

  return $items;
}
/*
 * implements hook_block_info
 */
function likeabee_resources_block_info() {
  //this is a really nasty temp hack to keep the resources section consistent with the groups section
  //simulating the menu system using a block for each menu item
  $default = array(
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'resources*',
    'regions' => array(
      'kaveret' => 'features'
    )
  );

  return array(
    'dashboard' =>  $default + array(
      'info' => 'Resources Dashboard',
      'weight' => 1,
    ),
    'my_beez' => $default + array(
      'info' => 'Resources My Beez',
      'weight' => 2,
    ),
    'marketplace' => $default + array(
      'info' => 'Resources Marketplace',
      'weight' => 3,
    )
  );
}
function likeabee_resources_block_view($delta) {
  switch ($delta) {
    case 'dashboard': $title = l(t('Dashboard'), 'resources');break;
    case 'my_beez': $title = l(t('My Beez'), 'resources/my_beez');break;
    case 'marketplace': $title = l(t('Marketplace'), 'resources/marketplace');break;
  }
  return array(
    'subject' => $title,
    'content' => "\n"
  );
}


/*
 * Implements views hook_views_api
 */
function likeabee_resources_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'likeabee_resources'),
  );
}
/*
 * implements hook_theme
 */
function likeabee_resources_theme() {
  return array(
    //this block provides a box around sections of a page
    'likeabee_page_block' => array(
      'variables' => array(
         'adv_help' => '',
         'title' => '',
         'content' => array()
      )
    )
  );
}

function likeabee_resources_help($path, $args) {

  if ($args[0] == 'resources') {
    //unhide the menu tabs!!!
    drupal_add_css('#page #main-menu{display:block;}', array('type' => 'inline'));
  }
  if ($path == 'resources') {
    $help[] = t('This is the local economy section. Here you can find what you need pay in Beez or in Shekels, or advertise yourself or your needs.');
    $help[] = t('Find out more about our currency, !beez', array('!beez' => l('Beez', 'help/beez')));
    return implode(' ', $help);
  }
}

/*
 * menu callback
 */
function resources_beeziest() {
  $build[] = array(
    '#markup' => views_embed_view('trade_analysis', 'system')
  );
  $build[] = array(
    '#markup' => views_embed_view('user_rankings', 'block_incomes')
  );
  $build[] = array(
    '#markup' => views_embed_view('user_rankings', 'block_expenditures')
  );
  $build[] = array(
    '#markup' => views_embed_view('user_rankings', 'block_volumes')
  );
  return $build;
}

/*
 * menu callback
 */
function resources_my_beez() {
  return array(
    'balances' => array(
      '#theme' => 'likeabee_page_block',
      '#title' => t('My BeeZ'),
      '#adv_help' => 'my_beez',
      '#content' => array(
        mcapi_balances_view($GLOBALS['user']->uid, array('def_drup')),
        array(
          '#theme' => 'balance_history',
          '#account' => $GLOBALS['user'],
          '#histories' => get_balance_history($GLOBALS['user'], array('def_drup')),
        )
      )
    ),
    'transactions' => array(
      '#theme' => 'likeabee_page_block',
      '#title' => t('My recent activities'),
      '#adv_help' => 'my_transactions',
      '#content' => array(
        array('#markup' => t('Available balance in BeeZ: @balance')),//this figure is given above
        array('#markup' => t('Total balance (all currencies, available and pending) converted to Shekels: @quant')),
        array('#markup' => views_embed_view('statement', 'default', $GLOBALS['user']->uid))
      )
    ),
    'pay' => array(
      '#theme' => 'likeabee_page_block',
      '#title' => t('My recent activities'),
      '#adv_help' => 'my_beez_pay',
      '#content' => array(
        '#markup' => drupal_render(mcapi_get_form('1stparty'))
      )
    )
  );
}


/*
 * menu_calback
 */
function theme_likeabee_page_block($vars) {
  $output = '<div class = "likeabee-block"><div class = "header">';
  $output .= $vars['title'];
  $output .= theme('advanced_help_topic', array('module' => 'likeabee_resources', 'topic' => $vars['adv_help']));
  $output .= '<div class = "content">'.drupal_render($vars['content']).'</div></div>';
  return $output;
}


function likeabee_resources_marketplace() {
  return 'This page will be a faceted search view of products. We could use the offers/wants module for now, but I think we should get on with installing commerce.';

}

function likeabee_resources_other() {
  return "This page is filling up space. could be used to show other people's transaction, system stats, special offers, or perhaps to talk about how many beez have been issued and redeemed.";
}


function likeabee_resources_transactions_alter(&$transactions) {
  //make a payment of 10% to payer and payee.
  //works for both bees and shekel payments
  $base_transaction = entity_metadata_create_transaction(array(
    'type' => 'likeabee_issue',
    'payer' => 1,
    'worth' => array('und' => array(0 => array(
      'quantity' => round($transactions[0]->worth['und'][0]['quantity'] / 10, 0, PHP_ROUND_HALF_UP),
      'currcode' => 'def_drup' //that means beez, the default currency
    )))
  ));
  $base_transaction->payee = $transactions[0]->payer;
  $transactions[] = clone($base_transaction);
  $base_transaction->payee = $transactions[0]->payee;
  $transactions[] = $base_transaction;
}
