<?php

define('MENU_BLOCK_MAIN_MENU_LEV1', 1);
define('MENU_BLOCK_MAIN_MENU_LEV2', 2);

function likeabee_help($path, $args) {
  if (substr($path, 0, 4) == 'user' && count(array_filter($args)) < 3) {
    return 'The accounting info on this page is duplicated in the resources section. This page needs theming. See user-profile.tpl.php';
  }
}

function likeabee_menu() {
  //just make a callback for the home page
  $items['home'] = array(
    'title' => 'temp home',
    'page callback' => 'temp_home',
    'access arguments' => array('access content')
  );
  return $items;
}

function likeabee_menu_alter(&$items) {
  $items['admin/content']['menu_name'] = 'localadmin';
  $items['admin/people']['menu_name'] = 'localadmin';
  $items['admin/config/system/backup_migrate/export']['menu_name'] = 'localadmin';
  $items['offers']['menu_name'] = 'community';//could be done in views_alter
  $items['wants']['menu_name'] = 'community';//could be done in views_alter
  $items['news']['menu_name'] = 'community';//could be done in views_alter
  $items['galleries']['menu_name'] = 'community';
  $items['docs']['menu_name'] = 'community';//could be done in views_alter
  $items['events-all']['menu_name'] = 'community';//could be done in views_alter
  $items['members']['menu_name'] = 'community'; //could be done in views_alter
}


function temp_home() {
  return l('Resources', 'resources');
}

function likeabee_node_view_alter(&$build, $node) {
  if ($build['#bundle'] != 'group') return; //this is needed to prevent nesting because group summary invokes a view with nodes in
  $build['section_chooser']['#weight'] = -1;
  $build['events'] = group_summary(t("Group's events"), 'event');
  $build['poll'] = group_summary(t("Group's polls"), 'poll');
  $build['video'] = group_summary(t("Group's videos"), 'video');
  $build['discussion'] = group_summary(t("Group's discussions"), 'discussion');
  $build['documents'] = group_summary(t("Group's documents"), 'document');
}
/*
function likeabee_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'likeabee'),
  );
}
*/


/*
 * implements hook_block_view
 * put the menu blocks in place
 */
function likeabee_block_view_alter(&$build, $block) {
  if ($block->module == 'cforge') $build = array();
}

function likeabee_block_info_alter($blocks, $theme) {
  unset($blocks['cforge']);
}