<?php
/*
 * implements hook_menu_alter
 * also see cforge_currencies_menu_links in cforge_currencies.install
 */
function cforge_currencies_menu_alter(&$items) {
  //$items['transact/1stparty']['menu_name'] = 'user-menu';
  //$items['transact/1stparty']['plid'] = 0;
  $items['transactions']['menu_name'] = 'main-menu';
  $items['transactions']['weight'] = 10;//this i sbeing ignored, which is a shame because the saved view menu item weighting isn't working either
  //to emulate what happened in d6, move all the mass pay menu items
  foreach (array('', '/one2many', '/many2one', '/one2few', '/few2one') as $arg) {
    $items['transact/masspay'.$arg] = $items['admin/accounting/masspay'.$arg];
    $items['transact/masspay'.$arg]['menu_name'] = 'user-menu';
    $items['transact/masspay'.$arg]['type'] = $arg == '/many2one' ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK;
    $items['transact/masspay'.$arg]['hidden'] = -1;
    unset($items['admin/accounting/masspay'.$arg]);
  }
  $items['user/%/statement']['title'] = 'Exchanges';
  unset($items['user/%/income_expenditure']);
}

/**
 * Implements hook_user_view().
 * Adds trading stats to the main user profile page.
 */
function cforge_currencies_user_view($account, $view_mode) {
  if (!currency_access('user_aggregated_view', 'def_drup')) return;
  $account->content['balance_history'] = array(
    '#theme' => 'balance_history',
    '#account' => $account,
    '#histories' => get_balance_history($account, array('def_drup')),
    '#weight' => 1
  );
  $account->content['limits'] = array(
    '#markup' => render(balance_limits_view($account->uid, array('def_drup'))),
    '#weight' => 2,
  );
  $account->content['balances'] = array(
    '#markup' => render(mcapi_balances_view($account->uid, array('def_drup'))),
    '#weight' => 3,
  );
  module_load_include('inc', 'mcapi_signatures');
  $account->content['pending_transactions'] = array(
    '#markup' => render(list_pending_for_uid($account->uid, array('def_drup'))),
    '#weight' => 4,
  );
}

/*
 * implements hook_form_FORM_ID_alter
 * fix the intertrading settings form against tampering
 */
function cforge_currencies_form_intertrade_settings_alter(&$form, $form_state) {
  $form['intertrading_server']['#disabled'] = TRUE;
  if ($intertrading_uid = &$form['undertrading_uid']['#default_value']) {
    $account = user_load($intertrading_uid);
    $form['intertrading_uid']['#description'] = t('Once this account has traded, this value cannot be changed.') .' '.
      t('Please ensure the mail for this account goes to a responsible person: @mail',
        array('@mail' => l($account->mail, "user/$account->uid/edit"))
    );
    $balances = mc_balances($account, variable_get('intertrading_cid'));
    if ($balances['count']) {
      $form['intertrading_uid']['#disabled'] = TRUE;
    }
  }
}


/*
 * Implements views hook_views_api
 */
function cforge_currencies_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'cforge_currencies'),
  );
}

/*
 * Implements ctools hook_ctools_plugin_api
 */
function cforge_currencies_ctools_plugin_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'cforge_currencies'),
  );
}


/*
 * implements hook_theme_registry_alter
 * injects the template files from the current module into the theme registry
 */
function cforge_currencies_theme_registry_alter(&$callbacks) {
  $path = drupal_get_path('module', 'cforge_currencies');
  $callbacks['balance_limits']['theme path'] = $path;
  $callbacks['balance_limits']['path'] = $path;
  $callbacks['balance_limits']['template'] = 'balance_limits';
}

function cforge_currencies_form_membership_subscription_options_alter(&$form, &$form_state) {

  $form['mcapi_member_fee_acc'] = array(
    '#type' => 'user_chooser_roles',
    '#args' => array(RID_SYSTEM),
    '#me' => TRUE,
  ) + $form['mcapi_member_fee_acc'];
  $form['mcapi_member_expenses_acc'] = array(
    '#type' => 'user_chooser_roles',
    '#args' => array(RID_SYSTEM),
    '#me' => TRUE,
  ) + $form['mcapi_member_expenses_acc'];

  $form['mcapi_member_fee_member_role']['#access'] = FALSE;
}

/*
 * implements hook_block_info_alter
 * overrides the saved block settings
 * see also hook_cf_block
 */
function ____cforge_currencies_block_info_alter(&$blocks, $theme, $code_blocks) {
  if ($theme != 'sky_seldulac') return;
  $blocks['mcapi']['balances']['region'] = 'sidebar_second';
  $blocks['mcapi']['balances']['status'] = 1;
  $blocks['mcapi']['balances']['visibility'] = BLOCK_VISIBILITY_LISTED;
  $blocks['mcapi']['balances']['pages'] = 'user/*';
  $blocks['mcapi_limits']['balance_limits']['region'] = 'sidebar_second';
  $blocks['mcapi_limits']['balance_limits']['status'] = 1;
  $blocks['mcapi_limits']['balance_limits']['visibility'] = BLOCK_VISIBILITY_LISTED;
  $blocks['mcapi_limits']['balance_limits']['pages'] = 'offers*\nwants\ntransactions';

}